## Numpy array with basics

In [ ]:
import numpy as np

In [3]:
arr_1d = np.array([1 , 2 ,3])
print(arr_1d)
arr_2d = np.array([[1 ,2 ,3] , [4 ,5 ,6]])
print(arr_2d)

[1 2 3]
[[1 2 3]
 [4 5 6]]


### python list vs numpy array

In [ ]:
py_list = [1 , 2 , 3 , 4 , 5]
print("python list multiply : " , py_list * 2) 
py_array = np.array([1 , 2 , 3 , 4 , 5])
print("numpy array multiply : " , py_array * 2) ### element wise operation

### python list operation
import time
start = time.time()
py_list = [i * 2 for i in range(1000000)]
print("\n List Operation time : " , time.time()- start)

### numpy array operation
start = time.time()
py_array = np.arange(1000000) * 2
print("\n Numpy Array Operation time : " , time.time()- start)

python list multiply :  [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
numpy array multiply :  [ 2  4  6  8 10]

 List Operation time :  0.08730697631835938

 Numpy Array Operation time :  0.00828862190246582


### Creating Array from Scratch

In [28]:
zeros = np.zeros((3 , 3))
print("\nZeros : \n" , zeros)

ones = np.ones((3 , 3))
print("\nOnes : \n" , ones)

full = np.full((3 , 3) , 7)
print("\nFull : \n" , full)

### identity matrix
eye = np.eye(3)
print("\nEye : \n" , eye)

### random matrix
random = np.random.random((3 , 3)) * 10
print("\nRandom : \n" , random)

### arange
arr = np.arange(0 , 20 , 2)
print("\nArange : \n" , arr)

### linspace
lin = np.linspace(0 , 1 , 3)  ### 4 values between 0 to 1
print("\nLinspace : \n" , lin)





Zeros : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Ones : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Full : 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Eye : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random : 
 [[2.40974436 8.21371026 6.39714133]
 [4.51450277 7.05648248 3.03315904]
 [0.56017269 6.85583884 8.04976376]]

Arange : 
 [ 0  2  4  6  8 10 12 14 16 18]

Linspace : 
 [0.  0.5 1. ]


### Vector Matrix and Array

In [40]:
### Vector
vector = np.array([1 , 2 , 3])
print("\nVector : \n" , vector)
### 2D array
matrix = np.array([[1 ,2 ,3] ,
                    [4 ,5 ,6] ,
                    [7 ,8 ,9]])
print("\n2D Array : \n" , matrix)

### tensor
tensor = np.array([
    [[1 ,2] , [3 ,4]] ,
    [[5 ,6] , [7 ,8]]])
print("\nTensor : \n" , tensor)


Vector : 
 [1 2 3]

2D Array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Tensor : 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [31]:
arr = np.array([[1 ,2 ,3] ,
                [4 ,5 ,6] ,
                [7 ,8 ,9]])
print("\nArray : \n" , arr.shape) ### (3 , 3)
print("\nNumber of dimensions : \n" , arr.ndim) ### 2  
print("\nSize of Array : \n" , arr.size) ### 9
print("\nData type of Array : \n" , arr.dtype) ### int32


Array : 
 (3, 3)

Number of dimensions : 
 2

Size of Array : 
 9

Data type of Array : 
 int64


### Array Reshaping

In [ ]:
arr = np.arange(9)
print("\nOriginal Array : \n" , arr)

reshaped = arr.reshape((3,3))
print("Reshaped Array : \n" , reshaped)

raval = reshaped.ravel()
print("Raveled Array : \n" , raval)

flatten = reshaped.flatten()
print("Flattened Array : \n" , flatten)

### transpose
transposed = reshaped.T
print("Transposed Array : \n" , transposed)




Original Array : 
 [0 1 2 3 4 5 6 7 8]
Reshaped Array : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Raveled Array : 
 [0 1 2 3 4 5 6 7 8]
Flattened Array : 
 [0 1 2 3 4 5 6 7 8]
