### Numpy Array Operations

In [1]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5])
print("Basics Slicing:", arr[1:4])  # Output: [2 3 4]
print("Advanced Slicing with Step:", arr[0:5:2])  # Output: [1 3 5]
print("Negative Indexing:", arr[-3:])  # Output: [3 4 5]

Basics Slicing: [2 3 4]
Advanced Slicing with Step: [1 3 5]
Negative Indexing: [3 4 5]


In [9]:
arr_2d = np.array([[1 ,2 ,3] ,
                   [4 , 5 , 6] ,
                   [7 , 8 , 9]])
print("2D Array Slicing \n" , arr_2d[1 ,1])
print("2D Array Row Slicing \n" , arr_2d[0:2 , 1:3])

2D Array Slicing 
 5
2D Array Row Slicing 
 [[2 3]
 [5 6]]


### Sorting

In [18]:
unsorted_arr = np.array([3, 1, 4, 5, 2])
sorted_arr = np.sort(unsorted_arr)
print("Unsorted Array:", unsorted_arr)
print("Sorted Array:", sorted_arr)

### 2D Sorting
unsorted_arr_2d = np.array([
    [3, 7, 4],
    [5, 2, 6]
])
sorted_arr_column = np.sort(unsorted_arr_2d , axis=0)  # Sort along columns    
sorted_arr_row = np.sort(unsorted_arr_2d , axis=1)  # Sort along rows
print("Unsorted 2D Array:\n", unsorted_arr_2d)
print("Sorted 2D Array along columns:\n", sorted_arr_column)
print("Sorted 2D Array along rows:\n", sorted_arr_row)


Unsorted Array: [3 1 4 5 2]
Sorted Array: [1 2 3 4 5]
Unsorted 2D Array:
 [[3 7 4]
 [5 2 6]]
Sorted 2D Array along columns:
 [[3 2 4]
 [5 7 6]]
Sorted 2D Array along rows:
 [[3 4 7]
 [2 5 6]]


### Filter

In [21]:
numbers = np.array([1, 2 ,3 , 4 , 5 , 6 , 7 , 8 , 9 , 10])
even_number = numbers[numbers % 2 == 0]
print("Even Numbers : " , even_number)

Even Numbers :  [ 2  4  6  8 10]


### Filter with Mask


In [22]:
mask = numbers > 5
print("Number greater than 5 : " , numbers[mask])

Number greater than 5 :  [ 6  7  8  9 10]


### Fancy Indexing vs np.Where()

In [ ]:
### indicing
indices = [0 , 2 , 5]
print("Fancy Indices : " , numbers[indices])

### np.where()
where_result = np.where(numbers > 5)
print("np.where() result : " , numbers[where_result])

### Conditional Array Creation
cond_array = np.where(numbers > 5 , numbers*5 , numbers)
print("Conditional Array : " , cond_array)

Fancy Indices :  [1 3 6]
np.where() result :  [ 6  7  8  9 10]
Conditional Array :  ['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even']
