Numpy Array and Basics

In [9]:
import numpy as np

Creating Array

In [6]:
arr_1D = np.array([1 ,2 , 3])
print("!D Array : \n" , arr_1D)
# 2D Array
arr_2D = np.array([[1 , 2 , 3] , [4 , 5 , 6]])
print("2D Array :\n" , arr_2D)

!D Array : 
 [1 2 3]
2D Array :
 [[1 2 3]
 [4 5 6]]


In [11]:
# Numpy Version
print(np.__version__)
# Check Dimension of Array.
print("2 Dimensional Array : " , arr_2D.ndim)
# Higher Dimensional Array.
hdarr = np.array([1 , 2 , 3 , 4 , 5] , ndmin=5)
print(hdarr)
print("Number of Dimension : " , hdarr.ndim)


2.3.3
2 Dimensional Array :  2
[[[[[1 2 3 4 5]]]]]
Number of Dimension :  5


# Numpy Array Indexing

In [30]:
# Array Indexing of !-D Array
arr = np.array([1 , 2 ,3 ,4 ,5])
print("Accessing !-D Array Element = " , arr[-1])
# Adding Index value.
print("Accessing and Adding !-D Array Element = " , arr[0] + arr[-1])
# Array Indexing of 2-D Array
arr_2 = np.array([[1 , 2 ,3] , [2 , 4 , 3]])
print( "Accessing 2-D Array Element [0][2] = " , arr_2[0][2])
print( "Accessing 2-D Array Element  by Another Way [0][2] = " , arr_2[0 , 2])

Accessing !-D Array Element =  5
Accessing and Adding !-D Array Element =  6
Accessing 2-D Array Element [0][2] =  3
Accessing 2-D Array Element  by Another Way [0][2] =  3


3-D Array and Indexing

In [37]:
arr_3 = np.array([[[1 , 2 , 3] , [2 ,4 ,5]] , [[1 ,2 ,4] , [4 , 3 , 6 ]]])
print(arr_3)
# Accessing 3-D Array Element
print("Accessing 3-D Array Element = " , arr_3[1 , 1 ,-1])

[[[1 2 3]
  [2 4 5]]

 [[1 2 4]
  [4 3 6]]]
Accessing 3-D Array Element =  6


# Numpy Array Slicing

In [41]:
num_slice = np.array([1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9])
print(num_slice[1:-1])
# Negetive Slicing
print(num_slice[-3:-1])

[2 3 4 5 6 7 8]
[7 8]


Slicing 2-D Array

In [50]:
num_slice_2D = np.array([[1 ,2 ,3] , [2 , 4 ,3 ] , [1 ,4 , 2]])
print("Slicing 2-D Array :" , num_slice_2D[1][0:])
print("Slicing 2-D Array :" , num_slice_2D[2 , :1])

Slicing 2-D Array : [2 4 3]
Slicing 2-D Array : [1]


# Numpy Data Type

In [56]:
arr_dt = np.array([1 ,2 ,3 ,5 ])
print(arr_dt.dtype)
# Creating an array with data type String
arr_string = np.array([1 ,2 ,3 ,5 ] , dtype="S")
# Converting a datatype in existing array
newArr = arr_string.astype("i")
print(newArr.dtype)
print(arr_string.dtype)

int64
int32
|S1


# Copy and View

In [60]:
arr_origional = np.array([1 , 3 , 4 , 6])
arr_copy = arr_origional.copy()
print(arr_copy)
# changing in copied array
arr_copy[0] = 23
print("Copy array : " , arr_copy)
print("Origional Array :" , arr_origional)
# Make a view change the origional array and display both array
arr_view = arr_origional.view()
arr_origional[0] = 43
print("View Array" , arr_view)
print("origional Array :" , arr_origional)


[1 3 4 6]
Copy array :  [23  3  4  6]
Origional Array : [1 3 4 6]
View Array [43  3  4  6]
origional Array : [43  3  4  6]


# Numpy Array Shapes

In [85]:
arr_2d_shape = np.array([[1 ,2 ,4] ,[2 ,5 ,6]])
print("2-D Array shape :" , arr_2d_shape.shape)
arr_3d_shape = np.array([[[2 ,3] , [3 ,2] ,[3 , 7]] ,
                        [[2 ,5] ,[4 ,7] , [7 , 8]] ,
                        [[2 ,5] ,[4 ,7] , [7 , 8]] ,
                        [[2 ,5] ,[4 ,7] , [7 , 8]]])
# In 3-D Array or Matrix
# how many 2-D Matrix used called depth ,
# how many 1-D Matrix used in 2-D Matrix called Rows
# how many Element  used in 1-D Matrix called Column
print("3-D Array shape :" , arr_3d_shape.shape)

# In 5-D Array or Matrix
# how many 4-D Matrix used called Level ,
# how many 3-D Matrix used in 4-D Matrix called Blocks
# how many 2-D Matrix used in 3-D Matrix called depth
# how many 1-D Matrix used in 2-D Matrix called Rows
# how many Element  used in 1-D Matrix called Column
arr_5d_shape = np.array([
                        [
                             [
                                [[2 ,3] , [3 ,2] ,[3 , 7]] ,
                                [[2 ,5] ,[4 ,7] , [7 , 8]] ,
                                [[2 ,5] ,[4 ,7] , [7 , 8]] ,
                                [[2 ,5] ,[4 ,7] , [7 , 8]]
                            ]
                        ] , 
                        [
                            [
                            [[2 ,3] , [3 ,2] ,[3 , 7]] ,
                            [[2 ,5] ,[4 ,7] , [7 , 8]] ,
                            [[2 ,5] ,[4 ,7] , [7 , 8]] ,
                            [[2 ,5] ,[4 ,7] , [7 , 8]]
                            ]
                        ]
                    ])
print("5-D Array shape :" , arr_5d_shape.shape)

2-D Array shape : (2, 3)
3-D Array shape : (4, 3, 2)
5-D Array shape : (2, 1, 4, 3, 2)


Reshaping the 1-D Array to 2-D , 3-D and 4-D

In [ ]:

arr_reshape = np.array([1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,3 , 2 ,4])
# Note if the element satisfy for 2d , 3d or 4d array then it reshape to it 
# otherwise it give error
# 2-D Reshape
# 4 * 3 satisfy it means 4 rows and 3 column
arr_2d_reshape = arr_reshape.reshape(4 , 3) 
print("2-D Reshaping : " , arr_2d_reshape)
# 3-D Reshape
# 3 * 2 * 2 satisfy it means 3 depth , 2 rows and 2 column
arr_3d_reshape = arr_reshape.reshape(3 , 2 , 2)
print("3-D Reshaping : " , arr_3d_reshape)
# 3-D Reshape
# 4 * 3 * 1 * 1 satisfy it means 4 block , 3 depth , 1 rows and 1 column
arr_4d_reshape = arr_reshape.reshape(4 , 3 , 1 , 1)
print("4-D Reshaping : " , arr_4d_reshape)


2-D Reshaping :  [[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 2 4]]
3-D Reshaping :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[9 3]
  [2 4]]]
4-D Reshaping :  [[[[1]]

  [[2]]

  [[3]]]


 [[[4]]

  [[5]]

  [[6]]]


 [[[7]]

  [[8]]

  [[9]]]


 [[[3]]

  [[2]]

  [[4]]]]


In [93]:
# if -1 given to the reshape function then it transform to 1-D Array
print("Flaterning the Array using reshape method :" , arr_3d_reshape.reshape(-1))
# changing Dimension using other method
print("Flaterning the Array using flatten method :" , arr_3d_reshape.flatten())
print("Flaterning the Array using ravel method :" , arr_3d_reshape.ravel())


Flaterning the Array using reshape method : [1 2 3 4 5 6 7 8 9 3 2 4]
Flaterning the Array using flatten method : [1 2 3 4 5 6 7 8 9 3 2 4]
Flaterning the Array using ravel method : [1 2 3 4 5 6 7 8 9 3 2 4]


# Array Itterating

In [99]:
# Iterate on the elements of the following 1-D array:
arr_1d_iter = np.array([1 ,2 , 3])
print("Loopin in 1-D Array :")
for n in arr_1d_iter:
    print(n)
# Iterate on the elements of the following 2-D array:
arr_2d_iter = np.array([[1 ,2 , 3] ,[3 ,5 , 9]])
print("Loopin in 2-D Array :")
for n in arr_2d_iter:
    print(n)
# looping each element of 2-D Array
for x in arr_2d_iter:
    for n in x :
        print(n)

Loopin in 1-D Array :
1
2
3
Loopin in 2-D Array :
[1 2 3]
[3 5 9]
1
2
3
3
5
9


3-D Array Iterating

In [107]:
arr_3d_iter = np.array([[[1 , 2 , 4] , [1 , 4 , 2]] , [[2 ,5 ,7] , [7 ,5 , 2]]])
print(arr_3d_iter)
# Accessing each depth of 3-D Array using loop.
for i in arr_3d_iter :
    print("Accessing each depth" , i)

# Accessing each rows of 3-D Array using loop.
for i in arr_3d_iter:
    for j in i:
        print("Accessing each rows" , j)

# Accessing each element of 3-D Array using loop.
for i in arr_3d_iter:
    for j in i:
        for k in j:
            print("Accessing each Element" , k)


[[[1 2 4]
  [1 4 2]]

 [[2 5 7]
  [7 5 2]]]
Accessing each depth [[1 2 4]
 [1 4 2]]
Accessing each depth [[2 5 7]
 [7 5 2]]
Accessing each rows [1 2 4]
Accessing each rows [1 4 2]
Accessing each rows [2 5 7]
Accessing each rows [7 5 2]
Accessing each Element 1
Accessing each Element 2
Accessing each Element 4
Accessing each Element 1
Accessing each Element 4
Accessing each Element 2
Accessing each Element 2
Accessing each Element 5
Accessing each Element 7
Accessing each Element 7
Accessing each Element 5
Accessing each Element 2


Iterating Arrays Using nditer()

In [ ]:
# in top block the variable is used arr_3d_iter
print("Iterating in 3-d array using np.nditer() method")
# We can not write like this
# for i in arr_3d_iter:
#     for j in i:
#         for k in j:
#             print("Accessing each Element" , k)
for n in np.nditer(arr_3d_iter):
    print(n)

Iterating in 3-d array using np.nditer() method
1
2
4
1
4
2
2
5
7
7
5
2


# Joining Arrays

In [142]:
arr_join1 = np.array([1 , 2 , 4 ])
arr_join2 = np.array([1 , 4 , 6 ])
#  Joining tow array
arr_join = np.concatenate((arr_join1 , arr_join2))
print("Concatinating 1-D Array :\n" , arr_join)
#  Join two 2-D arrays along rows (axis=1):
arr_2d_join1 = np.array([[1 , 2 ,3] , [2 , 5 ,7]])
arr_2d_join2 = np.array([[1 , 1 ,3] , [2 , 9 ,7]])
arr_join = np.concatenate((arr_2d_join1 , arr_2d_join2) , axis=1)
print("Join two 2-D arrays along rows (axis=1):\n" , arr_join)
#  Join two 2-D arrays along columns (axis=0):
arr_join = np.concatenate((arr_2d_join1 , arr_2d_join2) , axis=0)
print("Join two 2-D arrays along Columns (axis=0):\n" , arr_join)


Concatinating 1-D Array :
 [1 2 4 1 4 6]
Join two 2-D arrays along rows (axis=1):
 [[1 2 3 1 1 3]
 [2 5 7 2 9 7]]
Join two 2-D arrays along Columns (axis=0):
 [[1 2 3]
 [2 5 7]
 [1 1 3]
 [2 9 7]]


Using stack method for array concatinate

In [149]:
# we use np.stack() method 
# Note :: stack and concatinate both make 1-D to 2-D using rows or column
# Note :: if axis = 1 then in stack method its a rows concatinating
arr_1d_stack1 = np.array([1 , 2 , 3])
arr_1d_stack2 = np.array([7 , 5 , 2])
# if you give a flag axis-1 it's a column concating
arr_stack_column = np.stack((arr_1d_stack1 , arr_1d_stack2) , axis=1)
print("join two array using column :\n" , arr_stack_column)
# if you dont give a flag axis then it automatically choose axis-0
arr_stack_row = np.stack((arr_1d_stack1 , arr_1d_stack2))
print(" join two array using row :\n", arr_stack_row)

join two array using column :
 [[1 7]
 [2 5]
 [3 2]]
 join two array using row :
 [[1 2 3]
 [7 5 2]]


# Spliting Numpy Array

In [157]:
arr_1d_split = np.array([1 , 9 ,2 ,3 ,4 ,5 ,6 ,7])
# while spliting the array using array_split() method
#  it takes two arguments one the original array 
# and a number (tell how many times to split) 
arrSplit = np.array_split(arr_1d_split , 4) 
# it returns an array of arraySplit 
# like [array[1 , 2] , [3 ,6]]
print(arrSplit)
# we can access arraySplit data by indexing 
print("First index of arraySplit : " , arrSplit[0])

# Similar for 2-D Array Spliting.
arr_2d_split = np.array([[1 ,2] , [2 ,4] , [1 ,7] , [8 , 6] , [0 ,8]])
arr2dSplit = np.array_split(arr_2d_split , 3)
print(arr2dSplit)

[array([1, 9]), array([2, 3]), array([4, 5]), array([6, 7])]
First index of arraySplit :  [1 9]
[array([[1, 2],
       [2, 4]]), array([[1, 7],
       [8, 6]]), array([[0, 8]])]


# Searching in Array

In [161]:
arr_1d_search = np.array([1 ,2 ,3 ,1 ,4 ,2,1])
# It search in array and return a tuples with index value
arr_search1 = np.where(arr_1d_search == 1)
print(arr_search1)

(array([0, 3, 6]),)


# Sorting in Array

In [5]:
arr_1d_sort = np.array([1 , 3 , 5 , 2 , 1 ,4])
# Note: This method returns a copy of the array, leaving the original array unchanged.
arr_sorted1 = np.sort(arr_1d_sort)
print("Sorting 1-D Array :\n" , arr_sorted1)

# Sorting 2-d Array
arr_2d_sort = np.array([[1 ,2 ,3] , [3 ,2 , 6] , [7 ,1 ,3]])
# it sort every rows like 1-D array
arr_sorted2 = np.sort(arr_2d_sort)
print("Sorting 2-D Array :\n" ,arr_sorted2)


Sorting 1-D Array :
 [1 1 2 3 4 5]
Sorting 2-D Array :
 [[1 2 3]
 [2 3 6]
 [1 3 7]]
