## Student Performance Analysis Using Numpy.

In [1]:
import numpy as np
# --------------------------------------
# Student Performance Analyze
# --------------------------------------
print("Student Performance Analyzer : \n")

# Student Array
students = np.array(["Manoj" , "Pankaj" , "Saroj" , "Pawan" , 
                    "Sawastika" , "Gaurab" , "Anil" , "Raja"])
# Subjects Array :
subjects = np.array(["Math" , "Computer" , "Science" , "English"])

# Student Marks :: Array
marks = np.array([
    [70 , 54 , 34 , 86] ,
    [70 , 41 , 53 , 86] ,
    [75 , 64 , 74 , 96] ,
    [72 , 57 , 74 , 68] ,
    [66 , 51 , 40 , 66] ,
    [90 , 94 , 91 , 86] ,
    [100 , 94 , 94 , 89] ,
    [79 , 94 , 84 , 86] ,
])
# Student Marks Matrix:
print("Student Marks Matrix :\n" , marks)
print("-" * 40)
# ---------------------------------------
# Average Marks of Students and Subjects
# ---------------------------------------
# calculate the overall percentage of a student
# the array contain all student percentage
student_avg = marks.mean(axis=1)
# calculate the average percentage students were achieved in a subject
subject_avg = marks.mean(axis=0)
print("Average Marks For each Student : \n")
for name , avg in zip(students , student_avg):
    print(f"{name} : {avg : .2f}")

print("\nAverage Marks per Subject:")
for sub , avg in zip(subjects , subject_avg):
    print(f"{sub} : {avg : .2f}")
print("-" * 40)

# ---------------------------------------
# Highest and Lowest Score
# ---------------------------------------

highest_score = marks.max()
lowest_score = marks.min()

print(f"Highest Score Overall: {highest_score}")
print(f"Lowest Score Overall: {lowest_score}")
print("-" * 40)

# ------------------------------------------
# Top Performer
# ------------------------------------------
# argmax return the index of max value in array.
top_student_index = np.argmax(student_avg)
print(f"{students[top_student_index]} is top performer with percentage {student_avg[top_student_index]}")
print("-" * 40)

# --------------------------------------------
# Pass / Fail Anaysis
# --------------------------------------------

PASS_MARK = 40

# Subject-wise pass (True if all subjects >= PASS_MARK)
subject_pass = ~np.any(marks < PASS_MARK, axis=1)

# Final pass condition
final_pass = subject_pass & (student_avg >= PASS_MARK)

print("Final Pass / Fail Status:")
for name, passed in zip(students, final_pass):
    status = "PASS" if passed else "FAIL"
    print(f"{name}: {status}")

print("-" * 40)

# -----------------------------
# 5. Grade Assignment
# -----------------------------

def assign_grade(avg):
    if avg >= 90:
        return "A+"
    elif avg >= 80:
        return "A"
    elif avg >= 70:
        return "B"
    elif avg >= 60:
        return "C"
    elif avg >= 40:
        return "D"
    else:
        return "F"

print("Final Grades:")
for name, avg, passed in zip(students, student_avg, final_pass):
    grade = assign_grade(avg) if passed else "F"
    print(f"{name}: {grade}")

print("-" * 40)

# -----------------------------
# 6. Summary Report
# -----------------------------

total_students = len(students)
pass_count = np.sum(final_pass)
fail_count = total_students - pass_count

print("Summary Report:")
print(f"Total Students: {total_students}")
print(f"Passed: {pass_count}")
print(f"Failed: {fail_count}")

Student Performance Analyzer : 

Student Marks Matrix :
 [[ 70  54  34  86]
 [ 70  41  53  86]
 [ 75  64  74  96]
 [ 72  57  74  68]
 [ 66  51  40  66]
 [ 90  94  91  86]
 [100  94  94  89]
 [ 79  94  84  86]]
----------------------------------------
Average Marks For each Student : 

Manoj :  61.00
Pankaj :  62.50
Saroj :  77.25
Pawan :  67.75
Sawastika :  55.75
Gaurab :  90.25
Anil :  94.25
Raja :  85.75

Average Marks per Subject:
Math :  77.75
Computer :  68.62
Science :  68.00
English :  82.88
----------------------------------------
Highest Score Overall: 100
Lowest Score Overall: 34
----------------------------------------
Anil is top performer with percentage 94.25
----------------------------------------
Final Pass / Fail Status:
Manoj: FAIL
Pankaj: PASS
Saroj: PASS
Pawan: PASS
Sawastika: PASS
Gaurab: PASS
Anil: PASS
Raja: PASS
----------------------------------------
Final Grades:
Manoj: F
Pankaj: C
Saroj: B
Pawan: C
Sawastika: D
Gaurab: A+
Anil: A+
Raja: A
------------------